config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :integrations
  resources :organisations

  resources :users

  root to: 'customers#index'

  resources :customers
  resources :integrations, only: [:index]


end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Customer < ActiveRecord::Base
end

app/models/integration.rb
# == Schema Information
#
# Table name: integrations
#
#  id              :integer          not null, primary key
#  name            :string(255)      default("")
#  api_key         :string(255)      default("")
#  subdomain       :string(255)      default("")
#  organisation_id :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class Integration < ActiveRecord::Base
  validates :name, :organisation_id, presence: true

  belongs_to :organisation

  def connected?
    subdomain && api_key && service.connected?
  end

  def service
    (name.capitalize + 'Service').constantize.new(self)
  end
end

app/models/organisation.rb
# == Schema Information
#
# Table name: organisations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Organisation < ActiveRecord::Base
  has_many :users
  has_many :integrations

  def recurly
    integrations.find_or_create_by(name: 'recurly')
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#  organisation_id        :integer
#

class User < ActiveRecord::Base
  # validates :organisation_id, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_reader :organisation_name

  belongs_to :organisation

  accepts_nested_attributes_for :organisation

  def recurly
    organisation.recurly
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u|
      u.permit(:password, :password_confirmation, :current_password,
      organisation: :name) 
    }
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController

  # TODO write test for this
  def index
    @recurly = current_user.organisation.integrations.find_or_create_by(name: 'recurly')
  end

  # TODO write test for this
  def update
    @integration = Integration.find(params[:id])
    if @integration.update(integration_params)
      redirect_to integrations_path, notice: 'Integration updated.'
    else
      redirect_to integrations_path, notice: 'Integration failed to update.'
    end
  end

  private
    def integration_params
      params.require(:integration).permit(:name, :api_key, :subdomain)
    end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:show, :edit, :update, :destroy]

  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1
  # PATCH/PUT /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation.destroy
    respond_to do |format|
      format.html { redirect_to organisations_url, notice: 'Organisation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisation_params
      params.require(:organisation).permit(:name)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController



  def create
    super do |resource|
      org = Organisation.create(name: params[:user][:organisation_name])
      org.users << resource
    end
  end

  protected

  # def update_resource(resource, params)
  #   resource.update_without_password(params)
  # end
  #
  # private
  #
  # def user_params
  #   params.require(:user).permit(:email, organisation: [:name])
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/integrations_helper.rb
module IntegrationsHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/customers/_form.html.haml
= simple_form_for(@customer) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
  .form-actions
    = f.button :submit

app/views/customers/edit.html.haml
%h1 Editing customer
= render 'form'
= link_to 'Show', @customer
|
\#{link_to 'Back', customers_path}

app/views/customers/index.html.haml
.dropdown.settings-dropdown
  %span.glyphicon.glyphicon-cog#dropdownMenu1.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
  %ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenu1", role: "menu"}
    %li{role: "presentation"}
      = link_to 'Integrations', integrations_path, role: 'menuitem', tabindex: '-1'
    %li.divider{role: "presentation"}
    %li{role: 'presentation'}
      = link_to 'Profile', edit_user_registration_path, role: 'menuitem', tabindex: '-1'
    %li.divider{role: "presentation"}
    %li{role: "presentation"}
      = link_to 'Sign out', destroy_user_session_path, method: :delete, role: 'menuitem', tabindex: '-1'

.new-customer
  = link_to 'New Customer', new_customer_path, class: 'btn btn-default'

.container
  %table.table.table-hover
    %tbody.customer
      - @customers.each do |customer|
        %tr.customer
          %td.name= link_to customer.name, customer

app/views/customers/new.html.haml
.super-center
  %h1 New customer
  = render 'form'
  = link_to 'Back', customers_path

app/views/customers/show.html.haml
.super-center
  %p#notice= notice
  %p
    %strong Name:
    = @customer.name
  = link_to 'Edit', edit_customer_path(@customer)
  |
  \#{link_to 'Back', customers_path}

app/views/integrations/index.html.haml
.super-center
  .bignav
    = link_to 'BACK', root_path
  %h3 Recurly

  - if @recurly.connected?
    %p.bg-success
      Connected
  - else
    %p.bg-danger
      Not connected

  = simple_form_for(@recurly) do |f|
    = f.input :api_key
    = f.input :subdomain
    = f.submit 'Update integration', class: 'btn btn-default'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Customerlink
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/organisations/_form.html.erb
<%= simple_form_for(@organisation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing organisation</h1>

<%= render 'form' %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.html.erb
<h1>Listing organisations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisations.each do |organisation| %>
      <tr>
        <td><%= organisation.name %></td>
        <td><%= link_to 'Show', organisation %></td>
        <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
        <td><%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.erb
<h1>New organisation</h1>

<%= render 'form' %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organisation.name %>
</p>

<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>